export interface FeedbackEntry {
  source: string;
  content: string;
  timestamp: number;
  user_id?: string;
  metadata?: string;
}

export const mockFeedback: FeedbackEntry[] = [
  // High-volume, low-severity (normal noise)
  {
    source: "GitHub",
    content: "Would be nice to have dark mode support",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "user123",
    metadata: JSON.stringify({ issue_number: 456, repo: "cloudflare/workers" }),
  },
  {
    source: "Discord",
    content: "The docs could be clearer about rate limits",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "discord_user_789",
  },
  {
    source: "Twitter",
    content: "Love the new Workers AI features! 🚀",
    timestamp: Date.now() - 3 * 60 * 60 * 1000,
    user_id: "@happy_dev",
  },
  {
    source: "Support",
    content: "How do I configure custom domains?",
    timestamp: Date.now() - 5 * 60 * 60 * 1000,
    user_id: "support_ticket_001",
  },
  {
    source: "GitHub",
    content: "Feature request: Add TypeScript types for the new API",
    timestamp: Date.now() - 6 * 60 * 60 * 1000,
    user_id: "user456",
    metadata: JSON.stringify({ issue_number: 789 }),
  },
  {
    source: "Discord",
    content: "Can someone help me with CORS configuration?",
    timestamp: Date.now() - 4 * 60 * 60 * 1000,
    user_id: "discord_user_123",
  },
  {
    source: "Support",
    content: "Billing question: When does the free tier reset?",
    timestamp: Date.now() - 7 * 60 * 60 * 1000,
    user_id: "support_ticket_002",
  },
  {
    source: "Twitter",
    content: "Just migrated to Workers, so much faster!",
    timestamp: Date.now() - 2 * 60 * 60 * 1000,
    user_id: "@migrating_dev",
  },
  {
    source: "GitHub",
    content: "Minor typo in the README on line 42",
    timestamp: Date.now() - 8 * 60 * 60 * 1000,
    user_id: "user789",
    metadata: JSON.stringify({ issue_number: 123 }),
  },
  {
    source: "Discord",
    content: "What's the best practice for handling secrets?",
    timestamp: Date.now() - 3 * 60 * 60 * 1000,
    user_id: "discord_user_456",
  },

  // Low-volume, high-severity (flying under the radar)
  {
    source: "Support",
    content: "URGENT: Production deployment failed after Workers update. Our entire API is down. Error: 'Auth timeout after deploy'. This is blocking all our customers.",
    timestamp: Date.now() - 1 * 60 * 60 * 1000,
    user_id: "enterprise_customer_001",
    metadata: JSON.stringify({ priority: "critical", customer_tier: "enterprise" }),
  },
  {
    source: "GitHub",
    content: "Critical bug: Workers AI responses are inconsistent - same prompt returns different results. This breaks our production ML pipeline. Issue #blocked",
    timestamp: Date.now() - 2 * 60 * 60 * 1000,
    user_id: "ml_team_lead",
    metadata: JSON.stringify({ issue_number: 999, labels: ["bug", "production", "blocker"] }),
  },
  {
    source: "Support",
    content: "Incident: D1 database queries timing out in production. Affecting 10k+ users. Need immediate assistance.",
    timestamp: Date.now() - 30 * 60 * 1000,
    user_id: "startup_cto",
    metadata: JSON.stringify({ severity: "P0", affected_users: 10000 }),
  },
  {
    source: "Discord",
    content: "🚨 PROD DOWN: Rate limiting suddenly changed behavior after docs update. Our app is getting 429s from legitimate traffic. This is a breaking change!",
    timestamp: Date.now() - 45 * 60 * 1000,
    user_id: "discord_enterprise_user",
  },
  {
    source: "Twitter",
    content: "@CloudflareDev Our production Workers are randomly failing with 'internal error'. No logs, no explanation. This is unacceptable for a paid plan. #blocked",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "@frustrated_dev",
  },

  // Medium severity, various sources
  {
    source: "GitHub",
    content: "Rate limiting documentation is confusing after the recent update. Many users are hitting limits unexpectedly.",
    timestamp: Date.now() - 12 * 60 * 60 * 1000,
    user_id: "user321",
    metadata: JSON.stringify({ issue_number: 555, upvotes: 15 }),
  },
  {
    source: "Support",
    content: "Developer Experience: Error messages don't help debug issues. Getting generic 'something went wrong' errors.",
    timestamp: Date.now() - 10 * 60 * 60 * 1000,
    user_id: "support_ticket_003",
  },
  {
    source: "Discord",
    content: "Pricing question: Why did our bill jump 3x this month? The limits page doesn't explain usage-based pricing clearly.",
    timestamp: Date.now() - 8 * 60 * 60 * 1000,
    user_id: "discord_user_999",
  },
  {
    source: "GitHub",
    content: "Feature request: Better observability for Workers. Need more detailed metrics and tracing.",
    timestamp: Date.now() - 15 * 60 * 60 * 1000,
    user_id: "user654",
    metadata: JSON.stringify({ issue_number: 777, upvotes: 8 }),
  },
  {
    source: "Support",
    content: "Things that look bad but aren't: The dashboard shows '0 requests' but our app is working fine. Just a display bug.",
    timestamp: Date.now() - 6 * 60 * 60 * 1000,
    user_id: "support_ticket_004",
  },
  {
    source: "Twitter",
    content: "The new AI Search feature is great, but the pricing is unclear. How much does it cost per query?",
    timestamp: Date.now() - 4 * 60 * 60 * 1000,
    user_id: "@curious_dev",
  },
  {
    source: "GitHub",
    content: "Breaking: Workers AI model responses changed format. Our parsing logic broke. Need migration guide.",
    timestamp: Date.now() - 20 * 60 * 60 * 1000,
    user_id: "user987",
    metadata: JSON.stringify({ issue_number: 888, labels: ["breaking-change"] }),
  },
  {
    source: "Discord",
    content: "Under the radar: Some Workers are slower than others with identical code. Not sure if it's our fault or platform issue.",
    timestamp: Date.now() - 9 * 60 * 60 * 1000,
    user_id: "discord_user_555",
  },
  {
    source: "Support",
    content: "Developer Experience: The local development experience doesn't match production. Hard to debug.",
    timestamp: Date.now() - 11 * 60 * 60 * 1000,
    user_id: "support_ticket_005",
  },
  {
    source: "Twitter",
    content: "Love Cloudflare but wish there was better integration with monitoring tools like Datadog",
    timestamp: Date.now() - 5 * 60 * 60 * 1000,
    user_id: "@monitoring_fan",
  },

  // ========== CLUSTER: Rate Limiting Issues ==========
  {
    source: "GitHub",
    content: "Getting 429 rate limit errors unexpectedly. Our traffic hasn't changed but suddenly hitting limits.",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    user_id: "user_rl_001",
    metadata: JSON.stringify({ issue_number: 1001, labels: ["rate-limit", "bug"] }),
  },
  {
    source: "Discord",
    content: "Rate limiting is too aggressive. We're getting throttled on normal API usage patterns.",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "discord_rl_001",
  },
  {
    source: "Support",
    content: "Why are we receiving 429 Too Many Requests errors? We're well within our plan limits according to the dashboard.",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    user_id: "support_rl_001",
    metadata: JSON.stringify({ ticket_type: "rate_limit" }),
  },
  {
    source: "Twitter",
    content: "@CloudflareDev Rate limits seem inconsistent - sometimes works fine, sometimes 429s. What's the actual limit?",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "@dev_rl_001",
  },
  {
    source: "GitHub",
    content: "Rate limit headers not being returned correctly. Can't implement proper retry logic without accurate rate limit info.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    user_id: "user_rl_002",
    metadata: JSON.stringify({ issue_number: 1002, labels: ["rate-limit", "api"] }),
  },
  {
    source: "Discord",
    content: "429 errors happening during deployment. Is there a separate rate limit for deploy operations?",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    user_id: "discord_rl_002",
  },
  {
    source: "Support",
    content: "Rate limiting documentation says 1000 req/min but we're getting throttled at 500. Which is correct?",
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    user_id: "support_rl_002",
  },
  {
    source: "GitHub",
    content: "Rate limit reset time is unclear. Getting 429s even after waiting the documented cooldown period.",
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000,
    user_id: "user_rl_003",
    metadata: JSON.stringify({ issue_number: 1003, upvotes: 12 }),
  },
  {
    source: "Twitter",
    content: "Rate limits changed without notice? Our app worked fine yesterday, today getting constant 429s.",
    timestamp: Date.now() - 9 * 24 * 60 * 60 * 1000,
    user_id: "@dev_rl_002",
  },
  {
    source: "Discord",
    content: "Can we get better visibility into rate limit usage? Dashboard doesn't show real-time rate limit status.",
    timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000,
    user_id: "discord_rl_003",
  },

  // ========== CLUSTER: Documentation Problems ==========
  {
    source: "GitHub",
    content: "Documentation for Workers AI is missing examples for streaming responses. Had to dig through source code.",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "user_doc_001",
    metadata: JSON.stringify({ issue_number: 2001, labels: ["documentation"] }),
  },
  {
    source: "Discord",
    content: "The API reference docs don't match the actual API behavior. Examples are outdated.",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    user_id: "discord_doc_001",
  },
  {
    source: "Support",
    content: "Can't find documentation on how to handle D1 database migrations. The guide is incomplete.",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    user_id: "support_doc_001",
  },
  {
    source: "Twitter",
    content: "Docs say one thing, API does another. Which one should I trust? @CloudflareDev",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    user_id: "@dev_doc_001",
  },
  {
    source: "GitHub",
    content: "Missing documentation for error codes. Getting error 10001 but no explanation anywhere.",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    user_id: "user_doc_002",
    metadata: JSON.stringify({ issue_number: 2002, labels: ["documentation", "error-codes"] }),
  },
  {
    source: "Discord",
    content: "The getting started guide assumes too much knowledge. Need more beginner-friendly examples.",
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    user_id: "discord_doc_002",
  },
  {
    source: "Support",
    content: "Documentation for environment variables is scattered across multiple pages. Need a single reference.",
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000,
    user_id: "support_doc_002",
  },
  {
    source: "GitHub",
    content: "API documentation doesn't show all available parameters. Found undocumented options by trial and error.",
    timestamp: Date.now() - 9 * 24 * 60 * 60 * 1000,
    user_id: "user_doc_003",
    metadata: JSON.stringify({ issue_number: 2003, upvotes: 8 }),
  },
  {
    source: "Twitter",
    content: "Wish the docs had more real-world examples, not just hello world. Show me production patterns!",
    timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000,
    user_id: "@dev_doc_002",
  },
  {
    source: "Discord",
    content: "Documentation search is broken. Can't find relevant pages even when I know they exist.",
    timestamp: Date.now() - 11 * 24 * 60 * 60 * 1000,
    user_id: "discord_doc_003",
  },

  // ========== CLUSTER: Deployment/Performance Issues ==========
  {
    source: "GitHub",
    content: "Deployments are taking 5+ minutes. Used to be instant. What changed?",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "user_deploy_001",
    metadata: JSON.stringify({ issue_number: 3001, labels: ["deployment", "performance"] }),
  },
  {
    source: "Support",
    content: "URGENT: Worker deployment failed with timeout error. Production is down.",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "support_deploy_001",
    metadata: JSON.stringify({ priority: "high", environment: "production" }),
  },
  {
    source: "Discord",
    content: "Deployments randomly fail with 'internal error'. No details, have to retry multiple times.",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    user_id: "discord_deploy_001",
  },
  {
    source: "Twitter",
    content: "Workers are slower after latest update. Response times increased from 50ms to 200ms.",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    user_id: "@dev_deploy_001",
  },
  {
    source: "GitHub",
    content: "Cold start times are inconsistent. Sometimes instant, sometimes 2+ seconds. Makes UX unpredictable.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    user_id: "user_deploy_002",
    metadata: JSON.stringify({ issue_number: 3002, labels: ["performance", "cold-start"] }),
  },
  {
    source: "Support",
    content: "Production Worker is timing out on requests that work fine locally. Performance degradation.",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    user_id: "support_deploy_002",
  },
  {
    source: "Discord",
    content: "Deployment status shows 'success' but changes aren't live. Have to wait 10+ minutes for updates.",
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    user_id: "discord_deploy_002",
  },
  {
    source: "GitHub",
    content: "Workers hitting memory limits unexpectedly. Same code worked fine last week.",
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000,
    user_id: "user_deploy_003",
    metadata: JSON.stringify({ issue_number: 3003, labels: ["memory", "performance"] }),
  },
  {
    source: "Twitter",
    content: "Deployment rollback doesn't work. Tried to revert but still seeing new broken code.",
    timestamp: Date.now() - 9 * 24 * 60 * 60 * 1000,
    user_id: "@dev_deploy_002",
  },
  {
    source: "Support",
    content: "Canary deployments not working as documented. Traffic split isn't respecting percentages.",
    timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000,
    user_id: "support_deploy_003",
  },

  // ========== CLUSTER: Pricing/Billing Questions ==========
  {
    source: "Support",
    content: "Our bill increased 5x this month but usage looks the same. Can someone explain the charges?",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "support_billing_001",
    metadata: JSON.stringify({ ticket_type: "billing" }),
  },
  {
    source: "Discord",
    content: "Pricing page doesn't explain how Workers AI charges work. Is it per request or per token?",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "discord_billing_001",
  },
  {
    source: "GitHub",
    content: "Need clarity on D1 database pricing. Free tier limits are unclear.",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    user_id: "user_billing_001",
    metadata: JSON.stringify({ issue_number: 4001, labels: ["pricing", "d1"] }),
  },
  {
    source: "Twitter",
    content: "How do I estimate costs before going to production? Pricing calculator would be helpful.",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    user_id: "@dev_billing_001",
  },
  {
    source: "Support",
    content: "Billing dashboard shows charges but no breakdown. What am I paying for exactly?",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    user_id: "support_billing_002",
  },
  {
    source: "Discord",
    content: "Free tier limits reset monthly but dashboard doesn't show when. Need better visibility.",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    user_id: "discord_billing_002",
  },
  {
    source: "GitHub",
    content: "Pricing tiers don't match feature availability. Some features require paid plan but not documented.",
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    user_id: "user_billing_002",
    metadata: JSON.stringify({ issue_number: 4002, labels: ["pricing", "documentation"] }),
  },
  {
    source: "Support",
    content: "Unexpected charges for bandwidth. Thought it was included in Workers plan.",
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000,
    user_id: "support_billing_003",
  },

  // ========== CLUSTER: Error Messages/Debugging ==========
  {
    source: "GitHub",
    content: "Error messages are too generic. 'Something went wrong' doesn't help debug production issues.",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "user_error_001",
    metadata: JSON.stringify({ issue_number: 5001, labels: ["error-handling", "developer-experience"] }),
  },
  {
    source: "Discord",
    content: "Getting 'internal server error' with no details. How am I supposed to fix this?",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "discord_error_001",
  },
  {
    source: "Support",
    content: "Error codes don't map to documentation. Getting error 50001 but can't find what it means.",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    user_id: "support_error_001",
  },
  {
    source: "Twitter",
    content: "Need better error context. Stack traces would help debug Worker failures.",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    user_id: "@dev_error_001",
  },
  {
    source: "GitHub",
    content: "Validation errors don't specify which field failed. Have to guess what's wrong.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    user_id: "user_error_002",
    metadata: JSON.stringify({ issue_number: 5002, labels: ["validation", "error-handling"] }),
  },
  {
    source: "Discord",
    content: "Error logs are truncated. Can't see full error message in dashboard.",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    user_id: "discord_error_002",
  },
  {
    source: "Support",
    content: "Timeout errors don't show what operation timed out. Makes debugging impossible.",
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    user_id: "support_error_002",
  },
  {
    source: "GitHub",
    content: "Need structured error responses. JSON errors would be easier to parse than HTML error pages.",
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000,
    user_id: "user_error_003",
    metadata: JSON.stringify({ issue_number: 5003, upvotes: 10 }),
  },

  // ========== CLUSTER: Authentication Issues ==========
  {
    source: "Support",
    content: "Authentication tokens expiring too quickly. Have to re-authenticate constantly.",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "support_auth_001",
    metadata: JSON.stringify({ ticket_type: "authentication" }),
  },
  {
    source: "GitHub",
    content: "API key authentication failing intermittently. Works sometimes, fails other times.",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "user_auth_001",
    metadata: JSON.stringify({ issue_number: 6001, labels: ["authentication", "bug"] }),
  },
  {
    source: "Discord",
    content: "OAuth flow broken. Redirect URL not working after recent update.",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    user_id: "discord_auth_001",
  },
  {
    source: "Twitter",
    content: "Auth timeout errors in production. Tokens seem valid but getting 401s.",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    user_id: "@dev_auth_001",
  },
  {
    source: "Support",
    content: "Permission errors unclear. Getting 403 but don't know which permission is missing.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    user_id: "support_auth_002",
  },
  {
    source: "GitHub",
    content: "JWT token validation failing. Tokens work fine with other services.",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    user_id: "user_auth_002",
    metadata: JSON.stringify({ issue_number: 6002, labels: ["authentication", "jwt"] }),
  },
  {
    source: "Discord",
    content: "API keys not rotating properly. Old keys still work after expiration.",
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    user_id: "discord_auth_002",
  },
  {
    source: "Support",
    content: "Multi-factor authentication not working. Can't enable 2FA on account.",
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000,
    user_id: "support_auth_003",
  },

  // ========== CLUSTER: Feature Requests ==========
  {
    source: "GitHub",
    content: "Feature request: Add TypeScript type definitions for all Workers APIs. Currently incomplete.",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "user_feature_001",
    metadata: JSON.stringify({ issue_number: 7001, labels: ["feature-request", "typescript"], upvotes: 25 }),
  },
  {
    source: "Discord",
    content: "Would love to see GraphQL support for Workers. REST is limiting for our use case.",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "discord_feature_001",
  },
  {
    source: "Twitter",
    content: "Dark mode for dashboard please! Staring at bright white all day hurts my eyes.",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    user_id: "@dev_feature_001",
  },
  {
    source: "GitHub",
    content: "Feature: WebSocket support for Workers. Need real-time capabilities.",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    user_id: "user_feature_002",
    metadata: JSON.stringify({ issue_number: 7002, labels: ["feature-request", "websocket"], upvotes: 18 }),
  },
  {
    source: "Support",
    content: "Request: Better integration with monitoring tools. Datadog, New Relic, etc.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    user_id: "support_feature_001",
  },
  {
    source: "Discord",
    content: "Would be great to have a CLI tool for managing Workers. Web UI is slow for bulk operations.",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    user_id: "discord_feature_002",
  },
  {
    source: "GitHub",
    content: "Feature request: Built-in rate limiting configuration per Worker. Currently have to implement manually.",
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    user_id: "user_feature_003",
    metadata: JSON.stringify({ issue_number: 7003, labels: ["feature-request"], upvotes: 12 }),
  },
  {
    source: "Twitter",
    content: "Please add support for scheduled/cron jobs. Need to run Workers on a schedule.",
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000,
    user_id: "@dev_feature_002",
  },
  {
    source: "GitHub",
    content: "Request: Environment variable management UI. Currently have to use API or CLI.",
    timestamp: Date.now() - 9 * 24 * 60 * 60 * 1000,
    user_id: "user_feature_004",
    metadata: JSON.stringify({ issue_number: 7004, labels: ["feature-request", "ui"], upvotes: 7 }),
  },
  {
    source: "Discord",
    content: "Feature idea: Preview deployments before going live. Test changes in staging environment.",
    timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000,
    user_id: "discord_feature_003",
  },

  // ========== CLUSTER: Database/D1 Issues ==========
  {
    source: "Support",
    content: "D1 database queries timing out frequently. Simple SELECT queries taking 5+ seconds.",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "support_db_001",
    metadata: JSON.stringify({ ticket_type: "database", severity: "high" }),
  },
  {
    source: "GitHub",
    content: "D1 connection pool exhausted errors. Can't handle concurrent requests properly.",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "user_db_001",
    metadata: JSON.stringify({ issue_number: 8001, labels: ["d1", "database", "bug"] }),
  },
  {
    source: "Discord",
    content: "D1 migrations failing silently. No error message, just doesn't apply changes.",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    user_id: "discord_db_001",
  },
  {
    source: "Twitter",
    content: "D1 database size limits unclear. Getting errors but dashboard shows plenty of space.",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    user_id: "@dev_db_001",
  },
  {
    source: "Support",
    content: "D1 backup/restore functionality missing. No way to recover from data loss.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    user_id: "support_db_002",
  },
  {
    source: "GitHub",
    content: "D1 transactions not working as expected. Rollback not happening on errors.",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    user_id: "user_db_002",
    metadata: JSON.stringify({ issue_number: 8002, labels: ["d1", "transactions"] }),
  },
  {
    source: "Discord",
    content: "D1 query performance degraded after recent update. Same queries now 10x slower.",
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    user_id: "discord_db_002",
  },
  {
    source: "Support",
    content: "D1 database connection limits reached. Can't scale beyond current usage.",
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000,
    user_id: "support_db_003",
  },

  // ========== CLUSTER: AI/Workers AI Issues ==========
  {
    source: "GitHub",
    content: "Workers AI responses inconsistent. Same prompt returns different results each time.",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "user_ai_001",
    metadata: JSON.stringify({ issue_number: 9001, labels: ["workers-ai", "bug"], upvotes: 15 }),
  },
  {
    source: "Support",
    content: "Workers AI model changed without notice. Our prompts stopped working correctly.",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "support_ai_001",
    metadata: JSON.stringify({ ticket_type: "workers-ai", priority: "high" }),
  },
  {
    source: "Discord",
    content: "AI responses are too slow. Taking 5+ seconds for simple text generation.",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    user_id: "discord_ai_001",
  },
  {
    source: "Twitter",
    content: "Workers AI API breaking change. Response format changed, broke our production code.",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    user_id: "@dev_ai_001",
  },
  {
    source: "GitHub",
    content: "Need more control over AI model parameters. Temperature, top_p, etc. not exposed.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    user_id: "user_ai_002",
    metadata: JSON.stringify({ issue_number: 9002, labels: ["workers-ai", "feature-request"] }),
  },
  {
    source: "Discord",
    content: "AI token limits unclear. Getting cut off mid-response with no warning.",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    user_id: "discord_ai_002",
  },
  {
    source: "Support",
    content: "Workers AI streaming not working. Responses hang and never complete.",
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    user_id: "support_ai_002",
  },
  {
    source: "GitHub",
    content: "AI model selection limited. Need access to more models for different use cases.",
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000,
    user_id: "user_ai_003",
    metadata: JSON.stringify({ issue_number: 9003, labels: ["workers-ai", "feature-request"], upvotes: 9 }),
  },

  // ========== CLUSTER: Local Development ==========
  {
    source: "GitHub",
    content: "Local development doesn't match production. Workers behave differently in wrangler dev.",
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    user_id: "user_local_001",
    metadata: JSON.stringify({ issue_number: 10001, labels: ["local-dev", "developer-experience"] }),
  },
  {
    source: "Discord",
    content: "wrangler dev is slow and crashes frequently. Hard to develop locally.",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    user_id: "discord_local_001",
  },
  {
    source: "Support",
    content: "Local debugging tools missing. Can't step through code or inspect variables.",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    user_id: "support_local_001",
  },
  {
    source: "Twitter",
    content: "Need better local testing. Can't test D1 or AI features without deploying.",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    user_id: "@dev_local_001",
  },
  {
    source: "GitHub",
    content: "Environment variables don't work the same locally vs production. Causes confusion.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    user_id: "user_local_002",
    metadata: JSON.stringify({ issue_number: 10002, labels: ["local-dev", "env-vars"] }),
  },
  {
    source: "Discord",
    content: "Local development server doesn't support all Workers features. Have to deploy to test.",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    user_id: "discord_local_002",
  },
];
